spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB

comment.avatar: /images/514.png

server:
  servlet:
    session:
      timeout: P1D
