spring:
  datasource:
    username: root
    password: shiguMYSQL52370@
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.51.194.110:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true

logging:
  level:
    root: info
    com.jinyu: debug
  file:
    name: log/blog-dev.log

server:
  port: 8080
  servlet:
    context-path: /blog
    session:
      timeout: P1D
  tomcat:
    max-http-form-post-size: -1